version: '3'
services:
  mysql:
    image: mysql:8.0
    container_name: line-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: nlnl
      MYSQL_USER: nlnl
      MYSQL_PASSWORD: nlnl
      MYSQL_DATABASE: nlnl
      TZ: Asia/Taipei
    ports:
      - 3306:3306
    volumes:
      - ./docker/data/mysql/:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
