name: CI

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: 'mysql://nlnl:nlnl@mysql:3306/nlnl'

    strategy:
      matrix:
        node-version: [20.x]

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: nlnl
          MYSQL_DATABASE: nlnl
          MYSQL_USER: nlnl
          MYSQL_PASSWORD: nlnl
        ports:
          - 3306:3306
        options: >-
          --health-cmd='mysqladmin ping --silent'
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: sudo apt-get update -qq && sudo apt-get install -y openssl libssl-dev
      - run: yarn
      - run: yarn prisma db push --force-reset && yarn prisma db seed && yarn prisma generate
      - run: yarn build
      - run: yarn test
